// <auto-generated />
using System;
using FirstApiProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstApiProj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808210930_SeedStudents")]
    partial class SeedStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstApiProj.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Gpa")
                        .HasColumnType("real");

                    b.Property<DateTime?>("InActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pakpattan",
                            CreatedAt = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gpa = 3.22f,
                            Name = "Muhammad Asad",
                            Section = "MB"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lahore",
                            CreatedAt = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gpa = 3.75f,
                            Name = "Nadim Jawad",
                            Section = "MA"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Karachi",
                            CreatedAt = new DateTime(2025, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gpa = 3.9f,
                            Name = "Ali Ahmed",
                            Section = "MB"
                        },
                        new
                        {
                            Id = 4,
                            Address = "FortAbbas",
                            CreatedAt = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gpa = 3.45f,
                            Name = "Hassan Raza",
                            Section = "MC"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Multan",
                            CreatedAt = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gpa = 3.6f,
                            Name = "Ayesha Malik",
                            Section = "MA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
